[package]
name = "copicol"
version = "0.3.0"
description = "Un gestionnaire de presse-papiers simple et rapide"
authors = ["Clément Toledano"]
edition = "2021"

[lib]
name = "copicol_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-global-shortcut = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-autostart = "2"
tauri-plugin-window-state = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
arboard = "3"
sha2 = "0.10"
regex = "1"
tauri-plugin-log = "2"
log = "0.4"

[target.'cfg(windows)'.dependencies]
clipboard-win = "5"

[profile.release]
strip = true
lto = true
codegen-units = 1
